apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/secilui/kryckely-iot-config.git
    targetRevision: HEAD
    path: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

